#!/bin/sh -e

python -m pytest --ignore venv -W ignore::DeprecationWarning --cov=minimizer --cov-report=term-missing ${@}
mypy minimizer --ignore-missing-imports --disallow-untyped-defs
black minimizer tests --check
